apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::437837113778:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-5QSCDTW27FUR
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::437837113778:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-06T20:21:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1827"
  uid: 9a2aacfb-398d-4e19-a934-5c029422988d
